# Core application properties
spring.application.name=plan-service
server.port=8081

# Database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/plan_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jackson.deserialization.fail-on-null-for-primitives=false